# Generated by Django 3.2.7 on 2021-10-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, error_messages={'null': 'This is an error message'}, max_length=200, null=True, unique=True)),
                ('description', models.TextField()),
                ('phone_number', models.PositiveIntegerField()),
                ('is_live', models.BooleanField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
