# Generated by Django 3.2.7 on 2021-10-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
