# Generated by Django 3.2.7 on 2021-10-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_review_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
